<section class="contact-strip"><div class="shell"><div><small>PARTICIPA</small><h2>La noticia también<br>la construyes tú.</h2></div><p>¿Tienes una denuncia, actividad o historia de tu barrio? Queremos conocerla.</p><a class="black-button" href="mailto:prensa@vecinoss.cl">Contactar a prensa →</a></div></section>
<footer class="site-footer"><div class="shell footer-grid"><div class="footer-brand"><img src="<?= url('/logo/logo.png') ?>" alt="VecinoSS"><p>Información local, cercana y útil para la Provincia de San Antonio.</p></div><nav aria-label="Secciones del sitio"><b>Explora</b><a href="<?= url('/categoria/noticias') ?>">Noticias</a><a href="<?= url('/videos') ?>">VecinoSS TV</a><a href="<?= url('/eventos') ?>">Agenda y eventos</a><a href="<?= url('/categoria/comunidad') ?>">Comunidad</a></nav><nav aria-label="Contacto"><b>Participa</b><a href="mailto:prensa@vecinoss.cl">Envía tu noticia</a><a href="mailto:prensa@vecinoss.cl">Contacto</a><a href="<?= url('/admin') ?>">Administración</a></nav></div><div class="shell footer-bottom"><span>© <?= date('Y') ?> VecinoSS</span><span>Provincia de San Antonio · Chile</span></div></footer>
<nav class="mobile-toolbar" aria-label="Navegación móvil">
  <a href="<?= url('/') ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5M5.5 10v10h13V10M9.5 20v-6h5v6"/></svg><span>Inicio</span></a>
  <a href="<?= url('/categoria/noticias') ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5"/></svg><span>Noticias</span></a>
  <a href="<?= url('/videos') ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m10 9 5 3-5 3z"/></svg><span>TV</span></a>
  <a href="<?= url('/categoria/comunidad') ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3.5 19c.4-4 2.2-6 5.5-6s5.1 2 5.5 6M14 14c3.5-.4 5.5 1.3 6 4"/></svg><span>Comunidad</span></a>
  <a href="<?= url('/eventos') ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5" width="16" height="15" rx="1"/><path d="M8 3v4M16 3v4M4 9h16M8 13h2M14 13h2M8 17h2"/></svg><span>Eventos</span></a>
</nav>
