USE vecinoss;
ALTER TABLE categories ADD COLUMN parent_id BIGINT UNSIGNED NULL AFTER description, ADD INDEX idx_categories_parent (parent_id), ADD CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL;
CREATE TABLE tags (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80) NOT NULL,slug VARCHAR(100) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE post_tags (post_id BIGINT UNSIGNED NOT NULL,tag_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(post_id,tag_id),CONSTRAINT fk_post_tags_post FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,CONSTRAINT fk_post_tags_tag FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE) ENGINE=InnoDB;
ALTER TABLE videos MODIFY description LONGTEXT, ADD COLUMN commune VARCHAR(40) NOT NULL DEFAULT 'San Antonio' AFTER description, ADD COLUMN format VARCHAR(40) NOT NULL DEFAULT 'Reportajes' AFTER commune;
INSERT INTO categories(name,slug,description,parent_id) VALUES
('VecinoSS TV','vecinoss-tv','Contenido audiovisual local.',NULL),('Emprendedores y Guía Local','guia-local','Directorio comercial y turístico.',NULL),('Eventos','eventos','Agenda provincial de actividades.',NULL),
('Actualidad comunal','actualidad-comunal',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='noticias') x)),('Emergencias','emergencias',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='noticias') x)),('Política local','politica-local',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='noticias') x)),
('Denuncias Ciudadanas','denuncias-ciudadanas',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='comunidad') x)),('Mascotas perdidas y adopciones','mascotas',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='comunidad') x)),('Historias de vecinos','historias-de-vecinos',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='comunidad') x)),('Salud y bienestar','salud-y-bienestar',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='comunidad') x)),('Consejos prácticos','consejos-practicos',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='comunidad') x));
INSERT IGNORE INTO categories(name,slug,description,parent_id) VALUES
('Deportes','deportes',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='noticias') x)),('Cultura','cultura',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='noticias') x)),('Seguridad','seguridad',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='noticias') x)),
('Emprendedores','emprendedores',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='guia-local') x)),('Turismo','turismo',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='guia-local') x)),('Restaurantes','restaurantes',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='guia-local') x)),('Servicios','servicios',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='guia-local') x)),('Ferias','ferias-locales',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='guia-local') x)),('Comercios','comercios',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='guia-local') x)),
('Eventos municipales','eventos-municipales',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='eventos') x)),('Actividades culturales','actividades-culturales',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='eventos') x)),('Ferias','ferias',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='eventos') x)),('Deportes','eventos-deportivos',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='eventos') x)),('Conciertos','conciertos',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='eventos') x)),('El Consejo del Vecino','consejo-del-vecino',NULL,(SELECT id FROM (SELECT id FROM categories WHERE slug='comunidad') x));
