USE vecinoss;

INSERT IGNORE INTO posts (category_id,user_id,title,slug,excerpt,body,image,status,featured,published_at) VALUES
((SELECT id FROM categories WHERE slug='eventos-municipales'),(SELECT id FROM users ORDER BY id LIMIT 1),'Municipio invita a jornada familiar en la Plaza de Armas','municipio-invita-jornada-familiar-plaza-armas','Música, juegos y servicios municipales formarán parte de una tarde abierta a toda la comunidad.','La jornada reunirá actividades recreativas para todas las edades y puntos de información de los principales servicios municipales. La entrada es liberada.','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80','published',0,DATE_SUB(NOW(),INTERVAL 12 HOUR)),
((SELECT id FROM categories WHERE slug='actividades-culturales'),(SELECT id FROM users ORDER BY id LIMIT 1),'Centro cultural abre inscripciones para talleres gratuitos','centro-cultural-talleres-gratuitos','La programación incluye fotografía, teatro y pintura para jóvenes y personas adultas.','Las inscripciones se realizarán durante la semana en el centro cultural. Los talleres cuentan con cupos limitados y materiales incluidos.','https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=80','published',0,DATE_SUB(NOW(),INTERVAL 13 HOUR)),
((SELECT id FROM categories WHERE slug='ferias'),(SELECT id FROM users ORDER BY id LIMIT 1),'Feria de productores locales llega este fin de semana','feria-productores-locales-fin-semana','Emprendedores de la provincia ofrecerán alimentos, artesanía y productos elaborados en el territorio.','La feria funcionará durante todo el fin de semana y contará con espacios de descanso, gastronomía y presentaciones para las familias.','https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=900&q=80','published',0,DATE_SUB(NOW(),INTERVAL 14 HOUR)),
((SELECT id FROM categories WHERE slug='eventos-deportivos'),(SELECT id FROM users ORDER BY id LIMIT 1),'Corrida familiar abre convocatoria para todas las edades','corrida-familiar-convocatoria-todas-edades','El encuentro deportivo contempla circuitos recreativos y competitivos por el borde costero.','La organización habilitó categorías infantiles, juveniles y adultas. La inscripción es gratuita y se recomienda asistir con ropa deportiva.','https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=80','published',0,DATE_SUB(NOW(),INTERVAL 15 HOUR)),
((SELECT id FROM categories WHERE slug='conciertos'),(SELECT id FROM users ORDER BY id LIMIT 1),'Bandas locales protagonizan concierto abierto en el anfiteatro','bandas-locales-concierto-abierto-anfiteatro','Una selección de artistas de la zona presentará sus nuevos trabajos en una jornada gratuita.','El concierto comenzará durante la tarde y reunirá distintos estilos musicales. La actividad es abierta a la comunidad y apta para todo público.','https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80','published',0,DATE_SUB(NOW(),INTERVAL 16 HOUR)),
((SELECT id FROM categories WHERE slug='actividades-culturales'),(SELECT id FROM users ORDER BY id LIMIT 1),'Biblioteca prepara cuentacuentos y actividades infantiles','biblioteca-cuentacuentos-actividades-infantiles','Niñas, niños y sus familias podrán participar en una mañana dedicada a la lectura.','La actividad incluye narración de cuentos, juegos creativos y un espacio para conocer las novedades de la biblioteca local. No requiere inscripción.','https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80','published',0,DATE_SUB(NOW(),INTERVAL 17 HOUR));
