<?php $shareUrl = (isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . url('/video/' . $video['id']); ?>
<article class="article video-detail shell">
    <div class="breadcrumbs"><a href="<?= url('/') ?>">Inicio</a> / <a href="<?= url('/#tv') ?>">VecinoSS TV</a></div>
    <header><small>VECINOSS TV</small><h1><?= e($video['title']) ?></h1><?php if ($video['description']): ?><p class="standfirst"><?= str_contains($video['description'], '<') ? $video['description'] : e($video['description']) ?></p><?php endif; ?><div class="byline">Publicado el <?= e(date_es($video['published_at'])) ?></div></header>
    <div class="share-bar" aria-label="Compartir este video"><span>Compartir</span><a class="share-facebook" href="https://www.facebook.com/sharer/sharer.php?u=<?= rawurlencode($shareUrl) ?>" target="_blank" rel="noopener" aria-label="Compartir en Facebook"><img src="<?= asset('images/social/facebook.svg') ?>" alt=""><b>Facebook</b></a><a class="share-x" href="https://twitter.com/intent/tweet?url=<?= rawurlencode($shareUrl) ?>&text=<?= rawurlencode($video['title']) ?>" target="_blank" rel="noopener" aria-label="Compartir en X"><img src="<?= asset('images/social/x.svg') ?>" alt=""><b>X</b></a><a class="share-whatsapp" href="https://wa.me/?text=<?= rawurlencode($video['title'] . ' ' . $shareUrl) ?>" target="_blank" rel="noopener" aria-label="Compartir por WhatsApp"><img src="<?= asset('images/social/whatsapp.svg') ?>" alt=""><b>WhatsApp</b></a><a class="share-email" href="mailto:?subject=<?= rawurlencode($video['title']) ?>&body=<?= rawurlencode($video['title'] . "\n\n" . $shareUrl) ?>" aria-label="Compartir por correo"><img src="<?= asset('images/social/email.svg') ?>" alt=""><b>Correo</b></a><button type="button" data-copy-url="<?= e($shareUrl) ?>" aria-label="Copiar enlace"><img src="<?= asset('images/social/link.svg') ?>" alt=""><b>Copiar enlace</b></button></div>
    <div class="video-player video-player-inline" data-video-inline data-video-url="<?= e($video['video_url']) ?>" data-video-title="<?= e($video['title']) ?>"><a class="black-button" href="<?= e($video['video_url']) ?>" target="_blank" rel="noopener">Abrir video en su plataforma ↗</a></div>
</article>

<?php if ($related): ?><section class="dark-section video-related"><div class="shell section"><div class="section-title"><div><small>CONTINÚA VIENDO</small><h2>Más de VecinoSS TV</h2></div></div><div class="video-grid">
<?php foreach ($related as $item): ?><article><a class="video-cover" href="<?= url('/video/'.$item['id']) ?>"><img src="<?= e(post_image($item['cover_image'])) ?>" alt="Portada de <?= e($item['title']) ?>"><span>▶</span></a><small>VECINOSS TV</small><h3><a href="<?= url('/video/'.$item['id']) ?>"><?= e($item['title']) ?></a></h3><a class="more" href="<?= url('/video/'.$item['id']) ?>">Ver contenido →</a></article><?php endforeach; ?>
</div></div></section><?php endif; ?>
